services:
  postgres:
    image: postgres
    container_name: database-learning
    environment:
      POSTGRES_DB: springapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: