services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: weixing5shishi
      POSTGRES_DB: hibernate_learning
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  redis:
#    image: redis:latest
#    container_name: redis-cache
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis-data:/data
#    command: redis-server --appendonly yes

  cassandra:
    image: cassandra:latest
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_DC=datacenter1
    volumes:
      - cassandra-data:/var/lib/cassandra

  mongodb:
    restart: always
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


volumes:
  postgres-data:
#  redis-data:
  cassandra-data:
  mongodb_data: